import { EventEmitter } from "../../stencil.core";
import { Page } from "../../model/Page.model";
import { Context } from "../../model/Context.model";
import { WFService } from "../../services/wf.service";
import { HttpService } from "../../services/http.service";
import { ModelService } from "../../services/model.service";
import { PersistanceService } from "../../services/persistance.service";
import { WFHandler } from "../../handlers/wf.handler";
import { WFLoaderHandler } from "../../handlers/wfLoader.handler";
export declare class SiriusWf {
    private ipcHistory;
    http: HttpService;
    context: Context;
    wfService: WFService;
    modelService: ModelService;
    persistance: PersistanceService;
    wfHandler: WFHandler;
    wfLoaderHandler: WFLoaderHandler;
    wfMessage: EventEmitter;
    page: Page;
    wfSessionId: string;
    baseUrl: string;
    apiKey: string;
    process: string;
    validateName(newValue: string, oldValue: string): void;
    addActivity(type: string, create: any): Promise<void>;
    goto(activity: string): Promise<void>;
    loadProcess(processDef: string | object, activity?: string): Promise<void>;
    loadUrl(process: string, activity?: string): Promise<import("../../model/Process.model").Process>;
    hydrate(process: string, sessionId: string, activity?: string): Promise<void>;
    dehydrate(sessionId: string): Promise<void>;
    ipc(process: string, next?: string): Promise<void>;
    completed(process: string): Promise<void>;
    componentWillLoad(): Promise<void>;
    private UUID;
    render(): any;
}
