/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppContent {
    'match': MatchResults;
  }
  interface AppHome {}
  interface AppLoader {}
  interface AppMenu {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppContentElement extends Components.AppContent, HTMLStencilElement {}
  var HTMLAppContentElement: {
    prototype: HTMLAppContentElement;
    new (): HTMLAppContentElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLoaderElement extends Components.AppLoader, HTMLStencilElement {}
  var HTMLAppLoaderElement: {
    prototype: HTMLAppLoaderElement;
    new (): HTMLAppLoaderElement;
  };

  interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {}
  var HTMLAppMenuElement: {
    prototype: HTMLAppMenuElement;
    new (): HTMLAppMenuElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-content': HTMLAppContentElement;
    'app-home': HTMLAppHomeElement;
    'app-loader': HTMLAppLoaderElement;
    'app-menu': HTMLAppMenuElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppContent {
    'match'?: MatchResults;
  }
  interface AppHome {}
  interface AppLoader {}
  interface AppMenu {}
  interface AppRoot {}

  interface IntrinsicElements {
    'app-content': AppContent;
    'app-home': AppHome;
    'app-loader': AppLoader;
    'app-menu': AppMenu;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-content': LocalJSX.AppContent & JSXBase.HTMLAttributes<HTMLAppContentElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-loader': LocalJSX.AppLoader & JSXBase.HTMLAttributes<HTMLAppLoaderElement>;
      'app-menu': LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


